export default{
    tipKorisnika:'',
    authenticated: false,
    searchTerm:'',
    userEmail:'',
    podaci:[],
    url:'',
    mojipodaci:[],
    profil:[],
    aktivnikorisnik: null,
    aktivnikorisnik1: '',
    owo:[],
    korisnickipodaci:[],
    status:'',
    aktivanoglas:'',
    napomena:'',
    tekst:'',
    tipoglasa:[],
    podaci1:[],
    uwu:[],
    napomena1:'',
    satnica:'',
    email:'',
    brtel:'',
    datumk:'',
    datum:'',
    grad:'',
    oib:'',
    poslodavac:'',
    putni:'',
    vrsta:'',
    prijava:'',
    prijave:[],
    prijave1:[],
    ocekivanje:'',
    status1:'',
    posted_at:'',
    cards1:[],
    id:null,
    razlog:'',
    cards2:[],
    ido:null,
    cardsds:[]
}